apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vehagn

resources:
  - service.yaml
  - http-route.yaml
  - deployment.yaml

configMapGenerator:
  - name: whoami-config
    namespace: vehagn
    literals:
      - WHOAMI_PORT_NUMBER=8080
