apiVersion: batch/v1
kind: Job
metadata:
  name: cowsay-job
  namespace: vehagn
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cowsay
          image: docker.io/grycap/cowsay
