apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: vehagn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      containers:
        - name: tandoor
          image: docker.io/vabene1111/recipes:2.0.1
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: tandoor-config
            - secretRef:
                name: tandoor-secret-key
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-creds
                  key: password
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              memory: 1Gi
