apiVersion: apps/v1
kind: Deployment
metadata:
  name: tandoor
  namespace: vehagn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tandoor
  template:
    metadata:
      labels:
        app: tandoor
    spec:
      containers:
        - name: tandoor
          image: vabene1111/recipes
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: tandoor-config
          resources:
            requests:
              cpu: 10m
              memory: 256Mi
            limits:
              memory: 512Mi
