apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vehagn

resources:
  - service.yaml
  - db-creds.yaml
  - http-route.yaml
  - deployment.yaml
  - tandoor-secret-key.yaml

configMapGenerator:
  - name: tandoor-config
    namespace: vehagn
    literals:
      - TANDOOR_PORT=8080
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=postgres

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: postgresql
    namespace: vehagn
    version: 16.7.24
    valuesFile: postgres-values.yaml
