apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vehagn

resources:
  - service.yaml
  - db-creds.yaml
  - http-route.yaml
  - deployment.yaml
  - tandoor-secret-key.yaml

configMapGenerator:
  - name: tandoor-config
    namespace: vehagn
    literals:
      - TANDOOR_PORT=8080
      - ALLOWED_HOSTS=*
      # - CORS_ALLOWED_ORIGINS=["https://tandoor.s9n.no", "http://localhost:8080"]
      - CORS_ALLOW_ALL_ORIGINS=1
      - CSRF_TRUSTED_ORIGINS=["https://tandoor.s9n.no", "http://localhost" ]
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangodb
      - POSTGRES_DB=postgres
  - name: nginx-config
    namespace: vehagn
    files: [ nginx/conf.d/Recipes.conf ]

helmCharts:
  - name: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    releaseName: postgresql
    namespace: vehagn
    version: 16.7.24
    valuesFile: postgres-values.yaml
