apiVersion: v1
kind: Service
metadata:
  name: recipes
  namespace: vehagn
spec:
  type: ClusterIP
  selector:
    app: tandoor
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: gunicorn
      port: 8080
      targetPort: gunicorn
